### ISSUE TITLE
Database IP address?

### ISSUE THREAD

**Issue by maxtheking** [bp2008/biupdatehelper#1]
Hi, currently my CCTV network (which the Blue Iris server lives on) has no access to the internet, but i'd like the server to be able to reach out to BIupdatehelper to send out stats, what IP address(es) do i need to whitelist so that my server can reach the database?

**Comment by bp2008** [comment]
It sends to biupdatehelper.hopto.org which is 158.69.223.151.  It should stay on that IP address unless the hosting provider changes things or unless I change to a new hosting provider, which I have no plans to do.

**Comment by maxtheking** [comment]
Thanks! I'll whitelist that IP on my router.
