### ISSUE TITLE
Blue Iris 5.X Support

### ISSUE THREAD

**Issue by gawainXX** [bp2008/biupdatehelper#2]
Thank you for your great project! I had to use it once with Blue iris 4.X when I had to roll back an update due to it breaking one of my cameras.

Do you plan to introduce support for Blue iris 5.X?

**Comment by bp2008** [comment]
As far as I know the only part that doesn't work fully with Blue Iris 5 already is the anonymous performance data upload (BI 5 moved some of the settings around) which is not really important.

**Comment by bp2008** [comment]
I've finally done a patch to improve BI 5 compatibility.  It was mainly to fix the update detection which was broken since about BI 5.1 which was released recently.  But I also fixed direct-to-disc being reported incorrectly in the performance data.
