### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Campbell-D** [bp2008/biupdatehelper#4]
Hi, tried installing BIUpdateHelper 1.8 on WIndows 2016 today and Windows Defender detected @Trojan:Win32/Masson.A!rfn
![Capture](https://user-images.githubusercontent.com/37194160/86918047-037e2600-c11e-11ea-970e-d3e722fa6887.PNG)

**Comment by bp2008** [comment]
False positive.  I spent some time investigating this a while ago and I had to remove most of the program's code before virustotal stopped detecting anything in it.
