### ISSUE TITLE
Customize backup target folder

### ISSUE THREAD

**Issue by maverick915** [bp2008/biupdatehelper#6]
Instead of backing up all files to the working directory, why not make the target folder configurable?  Creating a backup on the local machine means you are still vulnerable to lose data if something happens to the local computer (theft, fire, power surge, etc...).

**Comment by bp2008** [comment]
Just run the program within the directory you want backups to be made in.  No need for more app complexity, I figure.

**Comment by bp2008** [comment]
Specifically, access to network drives can be spotty, and it would require people to change the user that the service runs as, so even enabling a backup target folder option would cause as many problems as it solves I think.

**Comment by maverick915** [comment]
That's fair. From a user's point of view it would be nice to do this all at once but it's not hard to setup separate backups to pull from the BiHelper directory.

**Comment by bp2008** [comment]
Do note you'll need to uninstall and reinstall the service via the buttons in the GUI, otherwise your existing service metadata will still point at the old exe path.
